version: "3.8"
services:

  # Apache with PHP
  apache:
    build:
      context: './apache-php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
#    networks:
#      - frontend
#      - backend
    ports:
      - ${APACHE_EXTERN_PORT}:80
    #      - 8080:8080
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./apache-php/conf/localhost.apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache-php/php.ini:/usr/local/etc/php/php.ini
    #    command: bash -c "chown www-data:www-data -R /var/www/html/"

    container_name: apache

  mysql:
    image: ${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_EXTERN_PORT}:3306
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
#    networks:
#      - backend
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_EXTERN_PORT}
      MYSQL_UNIX_PORT: ${MYSQL_EXTERN_PORT}
    container_name: mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_EXTERN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 5000M
#    networks:
#      - frontend
#      - backend
    container_name: phpmyadmin


#networks:
#  frontend:
#  backend:
#    name: backend
#    external: true
volumes:
  data:
